#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Wooblay Runtime – EC2 Bootstrap Script
#
# Runs on first boot of a hardened EC2 instance. Sets up:
#   1. Docker + docker-compose
#   2. Fetches tenant config from Secrets Manager
#   3. Pulls container images from ECR
#   4. Starts the Wooblay stack (Gate + Agent + Postgres)
#   5. Applies iptables network isolation for the agent container
#   6. Configures CloudWatch agent for log shipping
#
# Template variables (injected by Terraform):
#   - tenant_name
#   - aws_region
#   - secret_arn
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail
exec > >(tee /var/log/wooblay-bootstrap.log) 2>&1

echo "============================================"
echo "  Wooblay Runtime Bootstrap"
echo "  Tenant:  ${tenant_name}"
echo "  Region:  ${aws_region}"
echo "  Time:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "============================================"

# ── Step 1: Install Docker ──────────────────────────────────────────────
echo "→ Step 1: Installing Docker..."
dnf update -y -q
dnf install -y -q docker jq aws-cli

systemctl enable docker
systemctl start docker

# Install docker-compose v2 plugin
COMPOSE_VERSION="v2.32.4"
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL "https://github.com/docker/compose/releases/download/$${COMPOSE_VERSION}/docker-compose-linux-aarch64" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

echo "  ✓ Docker $(docker --version) installed"
echo "  ✓ Compose $(docker compose version) installed"

# ── Step 2: Fetch tenant config from Secrets Manager ────────────────────
echo "→ Step 2: Fetching tenant config from Secrets Manager..."
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "${secret_arn}" \
  --region "${aws_region}" \
  --query 'SecretString' \
  --output text)

DB_USER=$(echo "$SECRET_JSON" | jq -r '.db_user')
DB_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.db_password')
DB_NAME=$(echo "$SECRET_JSON" | jq -r '.db_name')
GATE_IMAGE=$(echo "$SECRET_JSON" | jq -r '.gate_image')
AGENT_IMAGE=$(echo "$SECRET_JSON" | jq -r '.agent_image')
SERVER_PRIVATE_KEY=$(echo "$SECRET_JSON" | jq -r '.wooblay_server_private_key')
SERVER_PUBLIC_KEY=$(echo "$SECRET_JSON" | jq -r '.wooblay_server_public_key')
TOOL_FILTER=$(echo "$SECRET_JSON" | jq -r '.tool_filter')
OPENAI_API_KEY=$(echo "$SECRET_JSON" | jq -r '.openai_api_key // empty')
OPENAI_MODEL=$(echo "$SECRET_JSON" | jq -r '.openai_model // "gpt-4o-mini"')

echo "  ✓ Config loaded for tenant: ${tenant_name}"
echo "  ✓ Gate image: $GATE_IMAGE"
echo "  ✓ Agent image: $AGENT_IMAGE"

# ── Step 3: Authenticate with ECR ──────────────────────────────────────
echo "→ Step 3: Authenticating with ECR..."
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
aws ecr get-login-password --region "${aws_region}" | \
  docker login --username AWS --password-stdin "$${ACCOUNT_ID}.dkr.ecr.${aws_region}.amazonaws.com"
echo "  ✓ ECR authenticated"

# ── Step 4: Pull images ────────────────────────────────────────────────
echo "→ Step 4: Pulling container images..."
docker pull "$GATE_IMAGE"
docker pull "$AGENT_IMAGE"
docker pull postgres:16-alpine
echo "  ✓ All images pulled"

# ── Step 5: Create compose environment file ─────────────────────────────
echo "→ Step 5: Creating runtime environment..."
RUNTIME_DIR="/opt/wooblay"
mkdir -p "$RUNTIME_DIR"

cat > "$RUNTIME_DIR/.env" <<ENVEOF
# Wooblay Runtime – ${tenant_name}
# Auto-generated by bootstrap. Do not edit manually.
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
GATE_IMAGE=$GATE_IMAGE
AGENT_IMAGE=$AGENT_IMAGE
WOOBLAY_SERVER_PRIVATE_KEY=$SERVER_PRIVATE_KEY
WOOBLAY_SERVER_PUBLIC_KEY=$SERVER_PUBLIC_KEY
WOOBLAY_TOOL_FILTER=$TOOL_FILTER
OPENAI_API_KEY=$OPENAI_API_KEY
OPENAI_MODEL=$${OPENAI_MODEL:-gpt-4o-mini}
ENVEOF

chmod 600 "$RUNTIME_DIR/.env"

# Write the compose file
cat > "$RUNTIME_DIR/docker-compose.yml" <<'COMPOSEEOF'
services:
  postgres:
    image: postgres:16-alpine
    container_name: wooblay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "$${DB_USER:-wooblay}"
      POSTGRES_PASSWORD: "$${DB_PASSWORD}"
      POSTGRES_DB: "$${DB_NAME:-wooblay}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-wooblay}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      gate_net:
        ipv4_address: 172.20.0.10
    deploy:
      resources:
        limits:
          memory: 512M

  gate:
    image: "$${GATE_IMAGE}"
    container_name: wooblay-gate
    restart: unless-stopped
    ports:
      - "4800:4800"
    environment:
      NODE_ENV: production
      PORT: "4800"
      DATABASE_URL: "postgresql://$${DB_USER:-wooblay}:$${DB_PASSWORD}@postgres:5432/$${DB_NAME:-wooblay}"
      WOOBLAY_SERVER_PRIVATE_KEY: "$${WOOBLAY_SERVER_PRIVATE_KEY}"
      WOOBLAY_SERVER_PUBLIC_KEY: "$${WOOBLAY_SERVER_PUBLIC_KEY}"
      OPENAI_API_KEY: "$${OPENAI_API_KEY:-}"
      OPENAI_MODEL: "$${OPENAI_MODEL:-gpt-4o-mini}"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4800/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      gate_net:
        ipv4_address: 172.20.0.20
      agent_net:
        ipv4_address: 172.21.0.20
    deploy:
      resources:
        limits:
          memory: 1G

  agent:
    image: "$${AGENT_IMAGE}"
    container_name: wooblay-agent
    restart: unless-stopped
    environment:
      GATE_URL: "http://172.21.0.20:4800"
      WOOBLAY_TOOL_FILTER: "$${WOOBLAY_TOOL_FILTER:-risky}"
      WOOBLAY_SIGNING_KEY_PATH: "/root/.wooblay/keys"
      WOOBLAY_AGENT_KEY_NAME: "wooblay-agent"
    depends_on:
      gate:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=256M
    networks:
      agent_net:
        ipv4_address: 172.21.0.30
    dns:
      - 8.8.8.8
    deploy:
      resources:
        limits:
          memory: 1536M

networks:
  gate_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  agent_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

volumes:
  pg_data:
    driver: local
COMPOSEEOF

echo "  ✓ Compose file written to $RUNTIME_DIR/docker-compose.yml"

# ── Step 6: Start the stack ────────────────────────────────────────────
echo "→ Step 6: Starting Wooblay stack..."
cd "$RUNTIME_DIR"
docker compose --env-file .env up -d

# Wait for Gate to become healthy
echo "  Waiting for Gate to become healthy..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:4800/health > /dev/null 2>&1; then
    echo "  ✓ Gate is healthy"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  ✗ Gate failed to become healthy after 60s"
    docker compose logs gate
    exit 1
  fi
  sleep 2
done

# ── Step 7: Apply iptables network isolation ────────────────────────────
echo "→ Step 7: Applying agent network isolation..."

AGENT_IP="172.21.0.30"
GATE_IP="172.21.0.20"

# Create custom chain
iptables -N WOOBLAY_AGENT 2>/dev/null || iptables -F WOOBLAY_AGENT

# Block EC2 metadata (CRITICAL)
iptables -A WOOBLAY_AGENT -s $AGENT_IP -d 169.254.169.254 -j DROP
iptables -A WOOBLAY_AGENT -s $AGENT_IP -d 169.254.170.2 -j DROP

# Block PostgreSQL network
iptables -A WOOBLAY_AGENT -s $AGENT_IP -d 172.20.0.0/24 -j DROP

# Allow agent -> Gate on port 4800
iptables -A WOOBLAY_AGENT -s $AGENT_IP -d $GATE_IP -p tcp --dport 4800 -j ACCEPT

# Allow DNS
iptables -A WOOBLAY_AGENT -s $AGENT_IP -p udp --dport 53 -j ACCEPT
iptables -A WOOBLAY_AGENT -s $AGENT_IP -p tcp --dport 53 -j ACCEPT

# Allow outbound HTTPS for model API calls
iptables -A WOOBLAY_AGENT -s $AGENT_IP -p tcp --dport 443 -j ACCEPT

# Allow established connections
iptables -A WOOBLAY_AGENT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Drop everything else
iptables -A WOOBLAY_AGENT -s $AGENT_IP -j DROP

# Insert chain
iptables -D FORWARD -j WOOBLAY_AGENT 2>/dev/null || true
iptables -I FORWARD 1 -j WOOBLAY_AGENT

echo "  ✓ Agent network isolation applied"

# ── Step 8: Persist iptables across reboots ────────────────────────────
dnf install -y -q iptables-services 2>/dev/null || true
iptables-save > /etc/sysconfig/iptables
systemctl enable iptables 2>/dev/null || true
echo "  ✓ iptables rules persisted"

# ── Step 9: Create systemd service for auto-restart ────────────────────
cat > /etc/systemd/system/wooblay-runtime.service <<'SERVICEEOF'
[Unit]
Description=Wooblay Runtime Stack
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/wooblay
ExecStart=/usr/local/lib/docker/cli-plugins/docker-compose --env-file /opt/wooblay/.env up -d
ExecStop=/usr/local/lib/docker/cli-plugins/docker-compose down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable wooblay-runtime
echo "  ✓ Systemd service created for auto-restart"

# ── Done ───────────────────────────────────────────────────────────────
echo ""
echo "============================================"
echo "  Wooblay Runtime Bootstrap Complete"
echo "  Tenant:  ${tenant_name}"
echo "  Gate:    http://localhost:4800"
echo "  Health:  http://localhost:4800/health"
echo "  Time:    $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "============================================"
