/**
 * Instance management routes.
 *
 * Manages deployed agent runtime instances. Each instance is an isolated
 * agent container running via Docker Compose with its own config and environment.
 *
 * GET    /api/instances              — List all instances
 * POST   /api/instances              — Create (provision) new instance
 * GET    /api/instances/:id          — Instance detail + status
 * PATCH  /api/instances/:id          — Update config
 * POST   /api/instances/:id/start    — Start instance container
 * POST   /api/instances/:id/stop     — Stop instance container
 * POST   /api/instances/:id/restart  — Restart instance
 * DELETE /api/instances/:id          — Teardown instance
 * GET    /api/instances/:id/logs     — Container logs
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { prisma } from '../db/client.js';
import { config } from '../config.js';
import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import { randomBytes } from 'crypto';

/**
 * Helper to resolve the current user's DB id from the Clerk-provided clerkUserId.
 * Returns null if not in platform mode or user doesn't exist.
 */
async function resolveUserId(request: FastifyRequest): Promise<string | null> {
  if (!config.PLATFORM_MODE) return null;
  const clerkId = request.clerkUserId;
  if (!clerkId) return null;
  const user = await prisma.user.findUnique({ where: { clerkId }, select: { id: true } });
  return user?.id ?? null;
}

/**
 * In platform mode, verify the requesting user owns the instance.
 * In instance mode, always returns true (no multi-user).
 */
async function checkInstanceOwnership(
  request: FastifyRequest,
  reply: FastifyReply,
  instanceId: string,
): Promise<{ instance: NonNullable<Awaited<ReturnType<typeof prisma.instance.findUnique>>> } | null> {
  const instance = await prisma.instance.findUnique({ where: { id: instanceId } });
  if (!instance) {
    reply.code(404).send({ error: 'Instance not found' });
    return null;
  }

  if (config.PLATFORM_MODE) {
    const userId = await resolveUserId(request);
    if (userId && instance.userId && instance.userId !== userId) {
      reply.code(403).send({ error: 'Access denied' });
      return null;
    }
  }

  return { instance };
}

// Base directory for per-instance configs
const INSTANCES_DIR = process.env['INSTANCES_DIR'] ?? '/opt/wooblay/instances';
const GATE_INTERNAL_URL = process.env['GATE_INTERNAL_URL'] ?? 'http://172.21.0.20:4800';
const BASE_AGENT_IMAGE = process.env['AGENT_IMAGE'] ?? 'wooblay-openclaw:latest';

// Docker compose project name (derived from /opt/wooblay -> "wooblay")
const COMPOSE_PROJECT = process.env['COMPOSE_PROJECT_NAME'] ?? 'wooblay';

// Port allocation: each instance gets a unique port on agent_net
// Base starts at 18800 and increments per instance
let nextPort = 18800;

function generateToken(): string {
  return randomBytes(32).toString('base64url');
}

function getInstanceDir(instanceId: string): string {
  return join(INSTANCES_DIR, instanceId);
}

function writeInstanceEnv(dir: string, config: Record<string, string>) {
  const lines = Object.entries(config)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k}=${v}`);
  writeFileSync(join(dir, '.env'), lines.join('\n') + '\n', 'utf-8');
}

function writeInstanceCompose(dir: string, instanceName: string, _port: number) {
  // The agent_net network is created by the main compose as "<project>_agent_net"
  const agentNetName = `${COMPOSE_PROJECT}_agent_net`;
  const compose = `# Auto-generated by Wooblay Gate for instance: ${instanceName}
services:
  agent-${instanceName}:
    image: ${BASE_AGENT_IMAGE}
    container_name: wooblay-agent-${instanceName}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GATE_URL: "${GATE_INTERNAL_URL}"
      INSTANCE_NAME: "${instanceName}"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=256M
    networks:
      - agent_net
    dns:
      - 8.8.8.8
    deploy:
      resources:
        limits:
          memory: 1536M

networks:
  agent_net:
    external: true
    name: ${agentNetName}
`;
  writeFileSync(join(dir, 'docker-compose.yml'), compose.trim() + '\n', 'utf-8');
}

export async function instanceRoutes(app: FastifyInstance): Promise<void> {
  // Ensure instances directory exists
  if (!existsSync(INSTANCES_DIR)) {
    try { mkdirSync(INSTANCES_DIR, { recursive: true }); } catch { }
  }

  /**
   * GET /api/instances — List all instances.
   */
  app.get('/api/instances', async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const userId = await resolveUserId(request);
      const instances = await prisma.instance.findMany({
        orderBy: { createdAt: 'desc' },
        ...(userId ? { where: { userId } } : {}),
      });

      // Enrich with live container status if possible
      let containerStatuses: Record<string, string> = {};
      try {
        const output = execSync('docker ps -a --format "{{.Names}}|{{.Status}}"', {
          timeout: 5000, stdio: 'pipe',
        }).toString();
        for (const line of output.trim().split('\n').filter(Boolean)) {
          const [name, status] = line.split('|');
          if (name) containerStatuses[name] = status;
        }
      } catch { }

      const enriched = instances.map((inst: typeof instances[number]) => ({
        ...inst,
        liveStatus: containerStatuses[`wooblay-agent-${inst.name}`] ?? null,
      }));

      return reply.send(enriched);
    } catch (err) {
      request.log.error(err, 'Failed to list instances');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  /**
   * POST /api/instances — Create (provision) a new agent instance.
   */
  app.post('/api/instances', async (request: FastifyRequest, reply: FastifyReply) => {
    const body = request.body as {
      name: string;
      agentRuntime?: string;
      model?: string;
      anthropicApiKey?: string;
      telegramBotToken?: string;
      telegramAllowedUsers?: string;
      telegramEnabled?: boolean;
      githubToken?: string;
      policyPreset?: string;
      configOverrides?: Record<string, string>;
      role?: string;
      goal?: string;
      awsAccessKeyId?: string;
      awsSecretAccessKey?: string;
      awsRegion?: string;
      gcpServiceAccountKey?: string;
      gcpProjectId?: string;
    };

    if (!body.name || typeof body.name !== 'string') {
      return reply.code(400).send({ error: 'Missing "name" field' });
    }

    const userId = await resolveUserId(request);

    // Sanitize name
    const name = body.name.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 32);

    try {
      // Check for duplicate name
      const existing = await prisma.instance.findUnique({ where: { name } });
      if (existing) {
        return reply.code(409).send({ error: `Instance "${name}" already exists` });
      }

      const port = nextPort++;
      const gatewayToken = generateToken();

      // Create instance record
      const instance = await prisma.instance.create({
        data: {
          name,
          userId: userId ?? undefined,
          status: 'provisioning',
          agentRuntime: body.agentRuntime ?? 'openclaw',
          model: body.model ?? 'claude-sonnet-4-20250514',
          role: body.role ?? null,
          configJson: JSON.stringify({
            port,
            gatewayToken,
            syncToken: generateToken(),    // for event sync back to platform
            anthropicApiKey: body.anthropicApiKey ? '***SET***' : '',
            githubPat: body.githubToken ? '***SET***' : '',
            telegramEnabled: body.telegramEnabled ?? false,
            telegramAllowedUsers: body.telegramAllowedUsers ?? '',
            policyPreset: body.policyPreset ?? 'balanced',
            goal: body.goal ?? '',
            ...body.configOverrides,
          }),
          telegramBot: body.telegramEnabled ? 'configured' : null,
          githubPat: !!body.githubToken,
          endpoint: `http://wooblay-agent-${name}:${port}`,
        },
      });

      // Create instance directory and config files
      const dir = getInstanceDir(instance.id);
      mkdirSync(dir, { recursive: true });

      // Parse config for goal/soul
      const goalFromConfig = body.configOverrides?.goal ?? '';

      const envConfig: Record<string, string> = {
        OPENCLAW_GATEWAY_TOKEN: gatewayToken,
        GATE_URL: GATE_INTERNAL_URL,
        WOOBLAY_TOOL_FILTER: 'risky',
        OPENCLAW_MODEL: body.model ?? 'claude-sonnet-4-20250514',
        TELEGRAM_ENABLED: String(body.telegramEnabled ?? false),
        INSTANCE_NAME: name,
        // Hybrid identity: seed role into agent's SOUL.md via entrypoint
        ...(body.role ? { OPENCLAW_AGENT_ROLE: body.role } : {}),
        ...(goalFromConfig ? { OPENCLAW_AGENT_GOAL: goalFromConfig } : {}),
        ...(body.anthropicApiKey ? { ANTHROPIC_API_KEY: body.anthropicApiKey } : {}),
        ...(body.telegramBotToken ? { TELEGRAM_BOT_TOKEN: body.telegramBotToken } : {}),
        ...(body.telegramAllowedUsers ? { TELEGRAM_ALLOWED_USERS: body.telegramAllowedUsers } : {}),
        ...(body.githubToken ? { GITHUB_TOKEN: body.githubToken } : {}),
        // Cloud provider credentials
        ...(body.awsAccessKeyId ? { AWS_ACCESS_KEY_ID: body.awsAccessKeyId } : {}),
        ...(body.awsSecretAccessKey ? { AWS_SECRET_ACCESS_KEY: body.awsSecretAccessKey } : {}),
        ...(body.awsRegion ? { AWS_DEFAULT_REGION: body.awsRegion } : {}),
        ...(body.gcpServiceAccountKey ? { GCP_SERVICE_ACCOUNT_KEY: body.gcpServiceAccountKey } : {}),
        ...(body.gcpProjectId ? { GCP_PROJECT_ID: body.gcpProjectId } : {}),
        ...(body.configOverrides ?? {}),
      };

      writeInstanceEnv(dir, envConfig);
      writeInstanceCompose(dir, name, port);

      // Start the container (synchronous to ensure it actually starts)
      try {
        execSync(`cd "${dir}" && docker compose up -d`, {
          timeout: 90_000,
          stdio: 'pipe',
        });

        // Get container ID
        let containerId: string | null = null;
        try {
          containerId = execSync(
            `docker ps -q --filter "name=wooblay-agent-${name}"`,
            { timeout: 5000, stdio: 'pipe' },
          ).toString().trim() || null;
        } catch { }

        await prisma.instance.update({
          where: { id: instance.id },
          data: { status: 'running', containerId },
        });
        request.log.info(`Instance ${name} started successfully`);

        // Return the updated instance
        const updated = await prisma.instance.findUnique({ where: { id: instance.id } });
        return reply.code(201).send(updated ?? instance);
      } catch (startErr: any) {
        request.log.error(startErr, `Failed to start instance ${name}`);
        await prisma.instance.update({
          where: { id: instance.id },
          data: { status: 'error' },
        });
        // Still return the instance (with error status) — UI can retry
        const errInstance = await prisma.instance.findUnique({ where: { id: instance.id } });
        return reply.code(201).send(errInstance ?? instance);
      }
    } catch (err) {
      request.log.error(err, 'Failed to create instance');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/instances/:id — Instance detail.
   */
  app.get('/api/instances/:id', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      // Get live container status
      let liveStatus: string | null = null;
      try {
        liveStatus = execSync(
          `docker ps -a --filter "name=wooblay-agent-${instance.name}" --format "{{.Status}}"`,
          { timeout: 5000, stdio: 'pipe' },
        ).toString().trim() || null;
      } catch { }

      return reply.send({ ...instance, liveStatus });
    } catch (err) {
      request.log.error(err, 'Failed to get instance');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  /**
   * PATCH /api/instances/:id — Update instance config.
   */
  app.patch('/api/instances/:id', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };
    const body = request.body as Partial<{
      name: string;
      model: string;
      agentRuntime: string;
      anthropicApiKey: string;
      telegramBotToken: string;
      telegramAllowedUsers: string;
      telegramEnabled: boolean;
      githubToken: string;
      configOverrides: Record<string, string>;
      role: string;
      goal: string;
      awsAccessKeyId: string;
      awsSecretAccessKey: string;
      awsRegion: string;
      gcpServiceAccountKey: string;
      gcpProjectId: string;
    }>;

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      // Update DB record
      const updateData: Record<string, unknown> = {};
      if (body.model) updateData.model = body.model;
      if (body.agentRuntime) updateData.agentRuntime = body.agentRuntime;
      if (body.role !== undefined) updateData.role = body.role || null;
      if (body.telegramEnabled !== undefined) {
        updateData.telegramBot = body.telegramEnabled ? 'configured' : null;
      }

      // Merge config
      const existingConfig = instance.configJson ? JSON.parse(instance.configJson) : {};
      const newConfig = {
        ...existingConfig,
        ...(body.model ? { model: body.model } : {}),
        ...(body.telegramEnabled !== undefined ? { telegramEnabled: body.telegramEnabled } : {}),
        ...(body.telegramAllowedUsers ? { telegramAllowedUsers: body.telegramAllowedUsers } : {}),
        ...(body.goal !== undefined ? { goal: body.goal } : {}),
        ...(body.configOverrides ?? {}),
      };
      updateData.configJson = JSON.stringify(newConfig);

      const updated = await prisma.instance.update({
        where: { id },
        data: updateData,
      });

      // Update the instance's .env file if it exists — merge with existing values
      const dir = getInstanceDir(id);
      if (existsSync(dir)) {
        // Read existing .env to preserve secrets not being updated
        const existingEnv: Record<string, string> = {};
        const envPath = join(dir, '.env');
        if (existsSync(envPath)) {
          const lines = readFileSync(envPath, 'utf-8').split('\n');
          for (const line of lines) {
            const idx = line.indexOf('=');
            if (idx > 0) {
              existingEnv[line.slice(0, idx)] = line.slice(idx + 1);
            }
          }
        }

        // Merge: existing values as base, overlay with new values
        const effectiveRole = body.role !== undefined ? (body.role || '') : (instance.role ?? '');
        const effectiveGoal = body.goal ?? newConfig.goal ?? '';
        // Check for evolved SOUL content stored from previous sessions
        const evolvedSoul = newConfig.evolvedSoul ?? '';

        const envConfig: Record<string, string> = {
          ...existingEnv,
          OPENCLAW_GATEWAY_TOKEN: existingEnv['OPENCLAW_GATEWAY_TOKEN'] ?? existingConfig.gatewayToken ?? generateToken(),
          GATE_URL: GATE_INTERNAL_URL,
          WOOBLAY_TOOL_FILTER: 'risky',
          OPENCLAW_MODEL: body.model ?? instance.model,
          TELEGRAM_ENABLED: String(body.telegramEnabled ?? existingConfig.telegramEnabled ?? false),
          INSTANCE_NAME: instance.name,
          // Hybrid identity: role seeds SOUL.md, evolved soul restores previous session
          ...(effectiveRole ? { OPENCLAW_AGENT_ROLE: effectiveRole } : {}),
          ...(effectiveGoal ? { OPENCLAW_AGENT_GOAL: effectiveGoal } : {}),
          ...(evolvedSoul ? { OPENCLAW_AGENT_SOUL: evolvedSoul } : {}),
          ...(body.anthropicApiKey ? { ANTHROPIC_API_KEY: body.anthropicApiKey } : {}),
          ...(body.telegramBotToken ? { TELEGRAM_BOT_TOKEN: body.telegramBotToken } : {}),
          ...(body.telegramAllowedUsers ? { TELEGRAM_ALLOWED_USERS: body.telegramAllowedUsers } : {}),
          ...(body.githubToken ? { GITHUB_TOKEN: body.githubToken } : {}),
          // Cloud provider credentials
          ...(body.awsAccessKeyId ? { AWS_ACCESS_KEY_ID: body.awsAccessKeyId } : {}),
          ...(body.awsSecretAccessKey ? { AWS_SECRET_ACCESS_KEY: body.awsSecretAccessKey } : {}),
          ...(body.awsRegion ? { AWS_DEFAULT_REGION: body.awsRegion } : {}),
          ...(body.gcpServiceAccountKey ? { GCP_SERVICE_ACCOUNT_KEY: body.gcpServiceAccountKey } : {}),
          ...(body.gcpProjectId ? { GCP_PROJECT_ID: body.gcpProjectId } : {}),
          ...(body.configOverrides ?? {}),
        };
        writeInstanceEnv(dir, envConfig);

        // ── Hot-inject vs restart ────────────────────────────────────────
        // A running agent may have hours of deep context. Restarting kills
        // all memory, sub-agents, and conversation state.
        //
        // What ACTUALLY works via docker exec:
        //   - File writes (AWS creds, GCP key, git config) — SDKs re-read
        //     these files on every request, so changes take effect immediately.
        //
        // What DOES NOT work via docker exec:
        //   - `export VAR=X` — only sets the var in that exec shell session,
        //     not in the running OpenClaw process (PID 1). Dies on exit.
        //   - openclaw.json edits — OpenClaw reads config at startup and
        //     caches it in memory. File changes are ignored until restart.
        //
        // Strategy:
        //   1. File-based creds → hot-inject (works, no restart)
        //   2. Env-var-only creds (Anthropic key) → requires restart
        //   3. Model / Telegram → requires restart (openclaw.json is cached)
        //   4. Role / Goal → DB + .env only; SOUL.md edited via Profile tab UI
        //
        // .env is ALWAYS updated so next cold start picks up everything.

        const containerName = `wooblay-agent-${instance.name}`;

        // These require restart because they need env vars or openclaw.json reload
        const needsRestart = !!(body.model || body.anthropicApiKey ||
          body.telegramBotToken || body.telegramEnabled !== undefined);

        if (instance.status === 'running') {
          // ── File-based hot-inject (reliably works) ─────────────────────
          const hotInjectCmds: string[] = [];

          // AWS credentials → write ~/.aws/credentials + config
          // AWS SDK reads these files on every API call — no restart needed
          if (body.awsAccessKeyId || body.awsSecretAccessKey) {
            const keyId = body.awsAccessKeyId ?? existingEnv['AWS_ACCESS_KEY_ID'] ?? '';
            const secret = body.awsSecretAccessKey ?? existingEnv['AWS_SECRET_ACCESS_KEY'] ?? '';
            const region = body.awsRegion ?? existingEnv['AWS_DEFAULT_REGION'] ?? 'us-east-1';
            if (keyId && secret) {
              hotInjectCmds.push(
                `mkdir -p /root/.aws`,
                `printf '[default]\\naws_access_key_id = ${keyId}\\naws_secret_access_key = ${secret}\\n' > /root/.aws/credentials`,
                `printf '[default]\\nregion = ${region}\\noutput = json\\n' > /root/.aws/config`,
              );
            }
          }

          // GCP credentials → write /root/gcp-key.json
          // Google SDK reads GOOGLE_APPLICATION_CREDENTIALS file path on every call.
          // The env var was set at container startup by entrypoint.sh, so as long
          // as we overwrite the file at the same path, it works.
          if (body.gcpServiceAccountKey) {
            hotInjectCmds.push(
              `echo '${body.gcpServiceAccountKey}' | base64 -d > /root/gcp-key.json 2>/dev/null || echo '${body.gcpServiceAccountKey}' > /root/gcp-key.json`,
            );
          }

          // GitHub token → update git credential helper (writes to ~/.gitconfig)
          // git reads this config file on every git operation — no restart needed
          if (body.githubToken) {
            hotInjectCmds.push(
              `git config --global credential.helper "!f() { echo \\"username=token\\"; echo \\"password=${body.githubToken}\\"; }; f"`,
            );
          }

          // Role / Goal → saved to DB + .env. The actual SOUL.md / IDENTITY.md
          // files are edited directly via the Profile tab in the UI, which uses
          // the /files/write API (base64 pipe into container). No shell escaping.

          // Execute file-based hot-inject
          if (hotInjectCmds.length > 0) {
            try {
              const script = hotInjectCmds.join(' && ');
              execSync(`docker exec "${containerName}" sh -c '${script.replace(/'/g, "'\\''")}'`, {
                timeout: 10_000, stdio: 'pipe',
              });
              request.log.info(`Instance ${instance.name} — hot-injected file-based credentials (no restart, memory preserved)`);
            } catch (injectErr: any) {
              request.log.error(injectErr, `Failed to hot-inject credentials into ${instance.name}`);
            }
          }

          // ── Restart only if truly unavoidable ──────────────────────────
          if (needsRestart) {
            try {
              execSync(`cd "${dir}" && docker compose up -d --force-recreate`, {
                timeout: 60_000, stdio: 'pipe',
              });
              request.log.info(`Instance ${instance.name} restarted (model/anthropic-key/telegram change requires restart)`);
            } catch (restartErr: any) {
              request.log.error(restartErr, `Failed to restart instance ${instance.name}`);
            }
          } else {
            request.log.info(`Instance ${instance.name} updated — no restart needed`);
          }
        }
      }

      return reply.send(updated);
    } catch (err) {
      request.log.error(err, 'Failed to update instance');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  /**
   * POST /api/instances/:id/start — Start instance container.
   * If instance dir is missing (e.g. after host migration), re-provision from DB then start.
   */
  app.post('/api/instances/:id/start', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      const dir = getInstanceDir(id);
      if (!existsSync(dir)) {
        // Re-provision after host migration: instance exists in DB but dir was on old host
        let config: { port?: number; gatewayToken?: string; goal?: string;[k: string]: unknown } = {};
        try {
          if (instance.configJson) config = JSON.parse(instance.configJson) as typeof config;
        } catch { }
        const port = config.port ?? nextPort++;
        mkdirSync(dir, { recursive: true });
        const envConfig: Record<string, string> = {
          OPENCLAW_GATEWAY_TOKEN: (config.gatewayToken as string) ?? generateToken(),
          GATE_URL: GATE_INTERNAL_URL,
          WOOBLAY_TOOL_FILTER: 'risky',
          OPENCLAW_MODEL: instance.model ?? 'claude-sonnet-4-20250514',
          TELEGRAM_ENABLED: String((config.telegramEnabled as boolean) ?? false),
          INSTANCE_NAME: instance.name,
          ...(instance.role ? { OPENCLAW_AGENT_ROLE: instance.role } : {}),
          ...(config.goal ? { OPENCLAW_AGENT_GOAL: String(config.goal) } : {}),
          ...(typeof config.anthropicApiKey === 'string' && config.anthropicApiKey && config.anthropicApiKey !== '***SET***' ? { ANTHROPIC_API_KEY: config.anthropicApiKey } : {}),
          ...(typeof config.githubToken === 'string' ? { GITHUB_TOKEN: config.githubToken } : {}),
          ...(typeof config.telegramBotToken === 'string' ? { TELEGRAM_BOT_TOKEN: config.telegramBotToken } : {}),
          ...(typeof config.telegramAllowedUsers === 'string' ? { TELEGRAM_ALLOWED_USERS: config.telegramAllowedUsers } : {}),
          ...(typeof config.awsAccessKeyId === 'string' ? { AWS_ACCESS_KEY_ID: config.awsAccessKeyId } : {}),
          ...(typeof config.awsSecretAccessKey === 'string' ? { AWS_SECRET_ACCESS_KEY: config.awsSecretAccessKey } : {}),
          ...(typeof config.awsRegion === 'string' ? { AWS_DEFAULT_REGION: config.awsRegion } : {}),
          ...(typeof config.gcpServiceAccountKey === 'string' ? { GCP_SERVICE_ACCOUNT_KEY: config.gcpServiceAccountKey } : {}),
          ...(typeof config.gcpProjectId === 'string' ? { GCP_PROJECT_ID: config.gcpProjectId } : {}),
        };
        writeInstanceEnv(dir, envConfig);
        writeInstanceCompose(dir, instance.name, port);
        request.log.info({ instanceId: id, name: instance.name }, 'Re-provisioned instance dir (was missing after migration)');
      }

      execSync(`cd "${dir}" && docker compose up -d`, { timeout: 30_000, stdio: 'pipe' });

      let containerId: string | null = null;
      try {
        containerId = execSync(
          `docker ps -q --filter "name=wooblay-agent-${instance.name}"`,
          { timeout: 5000, stdio: 'pipe' },
        ).toString().trim() || null;
      } catch { }

      await prisma.instance.update({
        where: { id },
        data: { status: 'running', containerId },
      });

      return reply.send({ ok: true, message: `Instance ${instance.name} started`, containerId });
    } catch (err: any) {
      request.log.error(err, 'Failed to start instance');
      return reply.code(500).send({ error: `Start failed: ${err.message}` });
    }
  });

  /**
   * POST /api/instances/:id/stop — Stop instance container.
   */
  app.post('/api/instances/:id/stop', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      const containerName = `wooblay-agent-${instance.name}`;
      try {
        execSync(`docker stop "${containerName}"`, { timeout: 15_000, stdio: 'pipe' });
      } catch { }

      await prisma.instance.update({
        where: { id },
        data: { status: 'stopped', containerId: null },
      });

      return reply.send({ ok: true, message: `Instance ${instance.name} stopped` });
    } catch (err: any) {
      request.log.error(err, 'Failed to stop instance');
      return reply.code(500).send({ error: `Stop failed: ${err.message}` });
    }
  });

  /**
   * POST /api/instances/:id/restart — Restart instance container.
   */
  app.post('/api/instances/:id/restart', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      const dir = getInstanceDir(id);
      if (!existsSync(dir)) {
        return reply.code(400).send({ error: 'Instance directory not found' });
      }

      execSync(`cd "${dir}" && docker compose restart`, { timeout: 30_000, stdio: 'pipe' });

      let containerId: string | null = null;
      try {
        containerId = execSync(
          `docker ps -q --filter "name=wooblay-agent-${instance.name}"`,
          { timeout: 5000, stdio: 'pipe' },
        ).toString().trim() || null;
      } catch { }

      await prisma.instance.update({
        where: { id },
        data: { status: 'running', containerId },
      });

      return reply.send({ ok: true, message: `Instance ${instance.name} restarted`, containerId });
    } catch (err: any) {
      request.log.error(err, 'Failed to restart instance');
      return reply.code(500).send({ error: `Restart failed: ${err.message}` });
    }
  });

  /**
   * DELETE /api/instances/:id — Teardown instance.
   */
  app.delete('/api/instances/:id', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      // Stop and remove container directly (faster than compose down)
      const containerName = `wooblay-agent-${instance.name}`;
      try {
        execSync(`docker stop "${containerName}" 2>/dev/null; docker rm "${containerName}" 2>/dev/null`, {
          timeout: 15_000, stdio: 'pipe',
        });
      } catch { }

      // Clean up instance directory
      const dir = getInstanceDir(id);
      if (existsSync(dir)) {
        try { rmSync(dir, { recursive: true, force: true }); } catch { }
      }

      await prisma.instance.delete({ where: { id } });

      return reply.code(204).send();
    } catch (err) {
      request.log.error(err, 'Failed to delete instance');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/instances/:id/logs — Get container logs.
   */
  app.get('/api/instances/:id/logs', async (request: FastifyRequest, reply: FastifyReply) => {
    const { id } = request.params as { id: string };
    const { tail } = request.query as { tail?: string };

    try {
      const instance = await prisma.instance.findUnique({ where: { id } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      const tailNum = tail ? parseInt(tail, 10) : 100;
      let logs = '';

      try {
        logs = execSync(
          `docker logs --tail ${tailNum} wooblay-agent-${instance.name} 2>&1`,
          { timeout: 10_000, stdio: 'pipe' },
        ).toString();
      } catch (err: any) {
        logs = err.stdout?.toString() ?? err.stderr?.toString() ?? 'No logs available';
      }

      return reply.send({ logs });
    } catch (err) {
      request.log.error(err, 'Failed to get instance logs');
      return reply.code(500).send({ error: 'Internal server error' });
    }
  });

  // ── Instance Secrets (agent-visible env vars) ─────────────────────────

  /**
   * GET /api/instances/:id/secrets — List instance env var keys (values are never returned).
   */
  app.get('/api/instances/:id/secrets', async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const { id } = request.params as { id: string };
      const instance = await prisma.instance.findUnique({ where: { id }, select: { secrets: true } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      let secrets: { key: string }[] = [];
      if (instance.secrets) {
        try {
          const parsed = JSON.parse(instance.secrets) as { key: string; encryptedValue: string }[];
          secrets = parsed.map(s => ({ key: s.key }));
        } catch { /* ignore corrupt data */ }
      }

      return reply.send({ secrets });
    } catch (err: any) {
      request.log.error({ err }, 'Failed to list instance secrets');
      return reply.code(500).send({ error: 'Failed to list secrets', detail: err.message });
    }
  });

  /**
   * POST /api/instances/:id/secrets — Add an env var to the instance.
   * Body: { key: string, value: string }
   */
  app.post('/api/instances/:id/secrets', async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const { id } = request.params as { id: string };
      const body = request.body as { key?: string; value?: string };

      if (!body.key || !body.value) {
        return reply.code(400).send({ error: 'key and value are required' });
      }

      const normalizedKey = body.key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, '_');
      if (!normalizedKey) return reply.code(400).send({ error: 'Invalid key name' });

      const instance = await prisma.instance.findUnique({ where: { id }, select: { secrets: true } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      let secrets: { key: string; encryptedValue: string }[] = [];
      if (instance.secrets) {
        try { secrets = JSON.parse(instance.secrets); } catch { /* ignore */ }
      }

      // Upsert — replace if key already exists
      secrets = secrets.filter(s => s.key !== normalizedKey);

      // Import envelope encrypt
      const { envelopeEncrypt } = await import('../services/vault.js');
      secrets.push({ key: normalizedKey, encryptedValue: envelopeEncrypt(body.value) });

      await prisma.instance.update({
        where: { id },
        data: { secrets: JSON.stringify(secrets) },
      });

      return reply.code(201).send({ key: normalizedKey });
    } catch (err: any) {
      request.log.error({ err }, 'Failed to add instance secret');
      return reply.code(500).send({ error: 'Failed to add secret', detail: err.message });
    }
  });

  /**
   * DELETE /api/instances/:id/secrets/:key — Remove an env var.
   */
  app.delete('/api/instances/:id/secrets/:key', async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const { id, key } = request.params as { id: string; key: string };

      const instance = await prisma.instance.findUnique({ where: { id }, select: { secrets: true } });
      if (!instance) return reply.code(404).send({ error: 'Instance not found' });

      let secrets: { key: string; encryptedValue: string }[] = [];
      if (instance.secrets) {
        try { secrets = JSON.parse(instance.secrets); } catch { /* ignore */ }
      }

      const before = secrets.length;
      secrets = secrets.filter(s => s.key !== key);
      if (secrets.length === before) {
        return reply.code(404).send({ error: `Secret ${key} not found` });
      }

      await prisma.instance.update({
        where: { id },
        data: { secrets: JSON.stringify(secrets) },
      });

      return reply.code(204).send();
    } catch (err: any) {
      request.log.error({ err }, 'Failed to delete instance secret');
      return reply.code(500).send({ error: 'Failed to delete secret', detail: err.message });
    }
  });
}
